name: Hello world workflow

on: push

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello world"
        run: pwd
        run: touch demo.py
        run: ls